#!/usr/bin/env python

#
#    CFNS - Rijkswaterstaat CIV, Delft © 2020 - 2021 <cfns@rws.nl>
#
#    Copyright 2020 - 2021 Jort Stuijt <jort.stuyt@gmail.com>
#
#    This file is part of DAB-communication-modules
#
#    DAB-communication-modules is free software: you can redistribute it and/or
#    modify it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    DAB-communication-modules is distributed in the hope that
#    it will be useful, but WITHOUT ANY WARRANTY; without even the implied
#    warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#    See the GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with DAB-communication-modules.
#    If not, see <https://www.gnu.org/licenses/>.
#

import argparse
import os
import subprocess

parser = argparse.ArgumentParser(description="This module can encrypt and descrypt strings with RSA.")
parser.add_argument("key", help="The key to encrypt/decrypt the string with.")
parser.add_argument("-e", "--encrypt", help="Encrypt a string")
parser.add_argument("-d", "--decrypt", help="Decrypt an encrypted string")
parser.add_argument("-v", "--verbose", help="Increase output verbosity.",
                    action="store_true")
args = parser.parse_args()

FILENAME = "../temp.encryption-module"


def vprint(*rgs, **kwrgs):
    if args.verbose:
        print(" ".join(map(str, rgs)), **kwrgs)


def to_file(text):
    with open(FILENAME, "w") as file:
        file.write(text)


def remove_file():
    os.remove(FILENAME)


def read_file(filename):
    output = ""
    with open(filename) as file:
        for line in file.readlines():
            output += line + "\n"
    return output[:-1]


def encrypt(key, string):
    to_file(string)
    command = ["gpg", "--pinentry-mode=loopback", "--no-symkey-cache", "--passphrase", key, "--symmetric",
               "--cipher-algo", "AES256", FILENAME]
    subprocess.run(command)

    return True


def get_formatted_command(command):
    result = ""
    for x in command:
        result += x.replace(" ", "\\ ") + " "
    return result[:-1]


def decrypt(key, string):
    output_filename = "../output.txt"
    command = ["gpg", "--pinentry-mode=loopback", "--passphrase", key, "-o", output_filename,
               "--decrypt", string]
    vprint("Running command:", get_formatted_command(command))
    subprocess.run(command)
    return read_file("../message.txt")


if args.encrypt is not None:
    vprint(f"Encrypting {args.encrypt} with {args.key}.")
    print(encrypt(args.key, args.encrypt))
    quit(0)
elif args.decrypt is not None:
    vprint(f"Decrypting {args.decrypt} with {args.key}.")
    print(decrypt(args.key, args.decrypt))
    quit(0)
else:
    print("No action specified.")
    quit(1)
